### ISSUE TITLE
Question: Configuring copy() arguments in copier.toml?

### ISSUE THREAD

**Issue by pykong** [jpscaletti/copier#34]
Can we specify any argument as required by the `copier()` function via the `copier.toml` file?
Except maybe for `src_path` and `dst_path`.

From the code, it seems only `_include` and `_exclude` are treated as arguments:
https://github.com/jpscaletti/copier/blob/3edbaabe70a294b1bab838d13c04de297573ff4e/copier/user_data.py#L86

Still, the readme mentions specifying the `data` argument in the `copier.toml`.

**Comment by pykong** [comment]
Now the `README.md` also talks about `_tasks` being fed into `copy()`.
What about other arguments?

**Comment by jpscaletti** [comment]
I'm ashamed to report that I didn't noticed those keys were ignored so the feature didn't work until this moment... See #36. 😞 
I fixed the bug in the newly released `2.4.2` and added the `_extra_paths` to the things you can configure in the `copier.yml` file.

So, to answer your question: "_exclude", "_include", "_tasks", and "_extra_paths" can take default values from the config file (`copier.yml` or alternatives). The rest of the keys defined in that file will be treated as questions to the user. The user will be queried about them (unless you use the `--force` flag).

If instead of the command line, you call the `copier.copy()` function, all of the above still applies but if you call the function with an "exclude", "include", "tasks", and/or "extra_paths" arguments, they will overwrite those defined in the `copier.yml` file.

**Comment by pykong** [comment]
Great! This saves us some typing when calling `copier` from the command line.
It is great to see how `copier` gets better and better with each commit.  ;-)
